name: "Osara (お皿)"
author: "wayne"

navigations:
  - title: Introduction
    href: "#introduction"
  - title: Features
    href: "#features"
  - title: Download
    href: "#download"
  - title: FAQ
    href: "#faq"
